### PR TITLE
Change the way of text manipulating

### PR DESCRIPTION
**Pull request by mzer0-yu**
Implemented something like std::string, e.g.

unsigned int strID_user_agent = alloc_string(void);
cs_page\* ptr_to_user_agent = get_page_ptr(strID_user_agent);
    \set_string(ptr_to_user_agent, "user agent"); /\* "user agent" _/
    \set_string(ptr_to_user_agent, " firefox"); /_ "user agent firefox" */
free_string(strID_user_agent);

### CODE REVIEW

**Comment by luohaha** [comment]
You can test all modify to make sure this program can run normally.

**Comment by luohaha** [comment]
Sorry, I am busy recently. I create a new branch `dev`, you can PR all modify into `dev`. When `dev` can work normally, I will merge it into `master`.

**Comment by luohaha** [comment]
不好意思，我必须保证`master`分支能够正常工作。然后，最近没有时间把你新提交的代码整合进去。所以，你可以把新的修改都提交到`dev`。如果你可以让`dev`正常跑起来，那就太感谢啦。最后等我有空再把`dev` 并入 `master`。你往`dev`提交的修改我都会merge的。

**Comment by luohaha** [comment]
如果你觉得其他部分写得不好的，都欢迎更改，只要保证对外的api不变就行。

**Comment by mzer0-yu** [comment]
By all means.

Anyway, I don't have an available test machine now, maybe @AntonioCS could have it tested.

Would you do this favor or not @AntonioCS. AMA in that conversation.

**Comment by mzer0-yu** [comment]
Replaced by this PR https://github.com/luohaha/CSpider/pull/27

**Comment by luohaha** [comment]
Thanks! I will test branch `dev` when i have free time.

**Comment by AntonioCS** [comment]
@mzer0-yu Sure

**Pull request closed without merging**
